# Generated by Django 4.1.1 on 2022-11-01 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_newuser_options_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='баланс'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активный'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 16, 23, 8, 356156, tzinfo=datetime.timezone.utc)),
        ),
    ]
