# Generated by Django 4.1.1 on 2022-11-26 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_alter_newuser_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 16, 2, 56, 907920, tzinfo=datetime.timezone.utc), verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='subscribe_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 16, 2, 56, 907920, tzinfo=datetime.timezone.utc), verbose_name='подписка до'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_image',
            field=models.ImageField(default='profile_image/user.png', upload_to='', verbose_name='фото профиля'),
        ),
    ]
