# Generated by Django 4.1.1 on 2022-12-06 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_alter_newuser_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPaymenr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25, verbose_name='почта')),
                ('bill_id', models.CharField(max_length=100, verbose_name='bill_id')),
                ('comment', models.CharField(max_length=100, verbose_name='коментарий')),
                ('subscribe', models.CharField(choices=[('BASIC', 'BASIC'), ('PREMIUM', 'PREMIUM')], max_length=7, verbose_name='тип подписки')),
            ],
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 9, 53, 0, 635244, tzinfo=datetime.timezone.utc), verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='subscribe_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 6, 9, 53, 0, 635244, tzinfo=datetime.timezone.utc), verbose_name='подписка до'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_image',
            field=models.ImageField(default='profile_image/user.png', upload_to='profile_image/', verbose_name='фото профиля'),
        ),
    ]
