# Generated by Django 4.1.1 on 2022-12-06 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_rename_checkpaymenr_checkpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 9, 56, 49, 742679, tzinfo=datetime.timezone.utc), verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='subscribe_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 6, 9, 56, 49, 742679, tzinfo=datetime.timezone.utc), verbose_name='подписка до'),
        ),
    ]
