# Generated by Django 4.1.1 on 2022-12-06 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0014_alter_newuser_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpayment',
            options={'verbose_name': 'Платежи', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 9, 57, 38, 159272, tzinfo=datetime.timezone.utc), verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='subscribe_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 6, 9, 57, 38, 159272, tzinfo=datetime.timezone.utc), verbose_name='подписка до'),
        ),
    ]
