# Generated by Django 4.1.1 on 2022-12-06 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0015_alter_checkpayment_options_alter_newuser_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpayment',
            name='subscribe',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 14, 2, 37, 230164, tzinfo=datetime.timezone.utc), verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='subscribe_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 6, 14, 2, 37, 230164, tzinfo=datetime.timezone.utc), verbose_name='подписка до'),
        ),
    ]
