# Generated by Django 4.1.1 on 2022-12-07 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0016_remove_checkpayment_subscribe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpayment',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='сумма пополнения'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 8, 17, 17, 569609, tzinfo=datetime.timezone.utc), verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='subscribe_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 8, 17, 17, 569609, tzinfo=datetime.timezone.utc), verbose_name='подписка до'),
        ),
    ]
