# Generated by Django 4.1.1 on 2022-12-07 09:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0017_checkpayment_amount_alter_newuser_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpayment',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(100)], verbose_name='сумма пополнения'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 9, 41, 58, 95347, tzinfo=datetime.timezone.utc), verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='subscribe_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 9, 41, 58, 95347, tzinfo=datetime.timezone.utc), verbose_name='подписка до'),
        ),
    ]
