# Generated by Django 4.1.1 on 2022-12-20 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0018_alter_checkpayment_amount_alter_newuser_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='название')),
                ('tou', models.CharField(max_length=100, verbose_name='описание')),
                ('file', models.FileField(upload_to='course/', verbose_name='файл курса')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 12, 20, 14, 38, 31, 465666, tzinfo=datetime.timezone.utc), verbose_name='дата курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 14, 38, 31, 464666, tzinfo=datetime.timezone.utc), verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='subscribe_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 14, 38, 31, 464666, tzinfo=datetime.timezone.utc), verbose_name='подписка до'),
        ),
    ]
