# Generated by Django 4.1.1 on 2022-12-23 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0021_alter_course_date_alter_course_file_alter_course_tou_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 13, 42, 15, 518663, tzinfo=datetime.timezone.utc), verbose_name='дата курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subscribe_type',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('PREMIUM', 'PREMIUM')], default='DEFAULT', max_length=7, verbose_name='тип подписки'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 13, 42, 15, 516663, tzinfo=datetime.timezone.utc), verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='subscribe_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 13, 42, 15, 516663, tzinfo=datetime.timezone.utc), verbose_name='подписка до'),
        ),
    ]
